"""remove_tiffin_unique_constraint

Revision ID: cd179dccff5e
Revises: 0001_init
Create Date: 2026-01-13 23:30:39.886013

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'cd179dccff5e'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tiffin_person_date_action'), 'tiffin_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_tiffin_person_date_action'), 'tiffin_logs', ['person_id', 'date', 'action'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
